name: flutter_app_than_so_hoc_2
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+14

environment:
  sdk: ">=2.16.0 <3.0.0"
#  flutter_datetime_picker: ^1.5.0
#    backdrop: ^0.5.3
#    intl: ^0.15.7
#    http: ^0.12.2
#    flutter_easyloading: ^2.2.2
dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: #^1.5.0
  backdrop: #^0.5.3
  intl: ^0.17.0
  http: #^0.12.2
  flutter_easyloading: #^2.2.2
  html: #^0.15.0
  flutter_html:
  google_mobile_ads: ^1.2.0
  dio: ^4.0.6

  #  flutter_view_widgets: ^1.0.6
#  flutter_webview_plugin: ^0.3.11

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_localizations: # Add this line
    sdk: flutter
  #firebase_messaging: ^10.0.0
  shared_preferences: #^2.0.6
  flutter_staggered_grid_view: ^0.6.2
  confetti: ^0.7.0
  flutter_animated_dialog: ^2.0.1
  google_fonts: ^3.0.1
#  appinio_swiper: ^1.1.1
  card_swiper: ^2.0.4
  url_launcher: ^6.1.7
  audioplayers: ^2.0.0
  shake: ^2.2.0
  vibration: ^1.7.6
  share_plus: ^6.3.0
  screenshot: ^1.3.0
  path_provider:
  auto_size_text:
  gallery_saver: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/icon_app.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  #generate: true # Add this line
  assets:
    - assets/
    - assets/chuc_tet/
    - assets/tet/
    - assets/tet/2x/
    - assets/tet/3x/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
